import info


class subinfo(info.infoclass):
    def setTargets( self ):
        for ver in ["3.4.1", "4.1"]:
            self.targets[ ver ] = f"https://ffmpeg.org/releases/ffmpeg-{ver}.tar.bz2"
            self.targetInstSrc[ ver ] = f"ffmpeg-{ver}"
        self.svnTargets['master'] = "https://git.ffmpeg.org/ffmpeg.git"
        self.targetDigests["3.4.1"] = (['f3443e20154a590ab8a9eef7bc951e8731425efc75b44ff4bee31d8a7a574a2c'], CraftHash.HashAlgorithm.SHA256)
        self.targetDigests["4.1"] = (['b684fb43244a5c4caae652af9022ed5d85ce15210835bce054a33fb26033a1a5'], CraftHash.HashAlgorithm.SHA256)
        self.description = "A complete, cross-platform solution to record, convert and stream audio and video."
        self.webpage = "https://ffmpeg.org/"
        self.defaultTarget = "4.1"

    def setDependencies( self ):
        self.buildDependencies["dev-utils/msys"] = None
        self.buildDependencies["dev-utils/nasm"] = None
        self.runtimeDependencies["virtual/base"] = None
        self.runtimeDependencies["libs/liblame"] = None
        self.runtimeDependencies["libs/libopus"] = None
        if CraftCore.compiler.isGCCLike():
            self.runtimeDependencies["libs/libsdl2"] = None
            self.runtimeDependencies["libs/libvorbis"] = None
            self.runtimeDependencies["libs/libvpx"] = None
            self.runtimeDependencies["libs/x264"] = None
            self.runtimeDependencies["libs/x265"] = None

from Package.AutoToolsPackageBase import *

class Package(AutoToolsPackageBase):
    def __init__( self, **args ):
        AutoToolsPackageBase.__init__( self )
        self.platform = ""
        self.subinfo.options.configure.noDataRootDir = True

        self.subinfo.options.configure.args = "--enable-shared \
                --disable-debug --disable-doc --enable-gpl --enable-version3 \
                --enable-avresample --enable-libmp3lame "
        if CraftCore.compiler.isMSVC():
            self.subinfo.options.configure.args += " --toolchain=msvc "
        else:
            # vorbis.pc & ogg.pc currently not generated by patch to use CMake
            self.subinfo.options.configure.args += " --enable-libopus --enable-libvorbis \
                --enable-libvpx --enable-libx264 --enable-libx265 "

